name: Backend CI

on:
  pull_request:
    branches: ["main"]
    paths:
      - "backend/**"
      - ".github/workflows/backend-ci.yml"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  changes:
    name: Check for Backend changes
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read

    outputs:
      backend: ${{ steps.filter.outputs.backend }}

    steps:
      - uses: actions/checkout@v4

      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            backend:
              - "backend/**"

  quality:
    name: Quality Checks
    runs-on: ubuntu-latest
    needs: changes
    if: ${{ needs.changes.outputs.backend == true }}

    defaults:
      run:
        working-directory: ./backend

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          version: "0.4.19"
          enable-cache: true

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: "./backend/.python-version"

      - name: Install dependencies
        run: uv sync --all-extras --dev

      - name: Run Ruff
        run: uv ruff check --output-format=github .

      - name: Run tests
        env:
          MONGO_CONNECTION_STRING: ${{ secrets.MONGO_CONNECTION_STRING }}
          GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
          GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
        run: uv run pytest -n auto --cov=src --cov-report=xml

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
